version: '3.8'

services:
  app:
    image: ghcr.io/anthropics/anthropic-quickstarts:computer-use-demo-latest
    container_name: anthropic
    env_file:
      - antropic-computer-use-demo.env
    ports:
      - "5900:5900"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    volumes:
      - type: bind
        source: $HOME/.anthropic
        target: /home/computeruse/.anthropic
