# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.2.0

# Cache settings: Set to true to enable caching
cache: true

# Example MCP Servers Object Structure
mcpServers:
  filesystem:
    # type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - /home/node/documents/
      - /home/node/notes/
  mcp-obsidian:
    command: npx
    args:
      - -y
      - "mcp-obsidian"
      - /home/node/notes/
